import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Breadcrumbs } from "@/components/Breadcrumbs";
import { Card } from "@/components/ui/Card";
import { ElementBadge } from "@/components/ElementBadge";
import { PalCard } from "@/components/PalCard";
import { PalImage } from "@/components/PalImage";
import { ReverseLookupTable } from "@/components/ReverseLookupTable";
import { allPals, getPalBySlug } from "@/lib/data/pals";
import { getParentPairsFor } from "@/lib/data/reverse-index";
import { buildMetadata } from "@/lib/seo/metadata";
import { getDescriptionFor } from "@/lib/seo/pal-description";
import {
  faqSchema,
  jsonLd,
  palSchema,
  type FaqEntry,
} from "@/lib/seo/structured-data";
import { getPalImageUrl } from "@/lib/data/pal-image-urls";
import type { Pal } from "@/types/pal";

interface Params {
  slug: string;
}

/**
 * Pre-render every Pal at build time. This is what makes the per-Pal pages
 * SEO-viable — they ship as static HTML with full metadata.
 */
export function generateStaticParams(): Params[] {
  return allPals.map((p) => ({ slug: p.slug }));
}

export function generateMetadata({ params }: { params: Params }): Metadata {
  const pal = getPalBySlug(params.slug);
  if (!pal) {
    return { title: "Pal not found" };
  }
  const elements = pal.elements.join(" / ");
  // SERP-optimized description: keep the species + paldex up front, end with
  // the action ("breeding combinations") to nudge clicks.
  const description = `${pal.name} (Paldex #${pal.paldexNo}) is a ${elements} type Palworld Pal with power value ${pal.powerValue}. See every parent pair, expected egg counts, and breeding plans.`;
  return buildMetadata({
    title: pal.name,
    description,
    canonical: `/pals/${pal.slug}`,
    ogType: "article",
    // Per-Pal OG image is generated by the sibling opengraph-image.tsx route;
    // Next.js wires it automatically via metadata so we don't need to set
    // `ogImage` here.
  });
}

export default function PalPage({ params }: { params: Params }) {
  const pal = getPalBySlug(params.slug);
  if (!pal) notFound();

  const pairs = resolvePairs(pal);
  const related = pickRelatedPals(pal, 6);
  const faqs = buildFaqs(pal, pairs.length);
  const description = getDescriptionFor(pal);
  const palImageForSchema = pal.imageUrl ?? getPalImageUrl(pal.id) ?? `/pals/${pal.slug}.png`;

  return (
    <div className="space-y-6">
      <Breadcrumbs
        crumbs={[
          { name: "Home", href: "/" },
          { name: "Pals", href: "/" },
          { name: pal.name, href: `/pals/${pal.slug}` },
        ]}
      />

      {/* Single H1 per page — the Pal's name. The PalCard intentionally uses
          h3 internally so we don't double up. */}
      <h1 className="sr-only">{pal.name}</h1>

      <PalCard pal={pal} />

      <section aria-labelledby="overview-heading">
        <h2 id="overview-heading" className="text-lg font-semibold">
          Overview
        </h2>
        <Card className="mt-2">
          <dl className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            <div>
              <dt className="text-xs uppercase text-[rgb(var(--muted))]">Paldex</dt>
              <dd className="mt-0.5">#{String(pal.paldexNo).padStart(3, "0")}</dd>
            </div>
            <div>
              <dt className="text-xs uppercase text-[rgb(var(--muted))]">
                Power value
              </dt>
              <dd className="mt-0.5">{pal.powerValue}</dd>
            </div>
            <div className="sm:col-span-2">
              <dt className="text-xs uppercase text-[rgb(var(--muted))]">
                Elements
              </dt>
              <dd className="mt-1 flex gap-1.5">
                {pal.elements.map((e) => (
                  <ElementBadge key={e} element={e} />
                ))}
              </dd>
            </div>
            <div className="sm:col-span-2">
              <dt className="text-xs uppercase text-[rgb(var(--muted))]">
                Breedable result
              </dt>
              <dd className="mt-0.5">
                {pal.breedable
                  ? "Yes — can appear from standard breeding."
                  : "No — special-combo only or variant."}
              </dd>
            </div>
          </dl>
        </Card>
      </section>

      <section aria-labelledby="about-heading">
        <h2 id="about-heading" className="text-lg font-semibold">
          About {pal.name}
        </h2>
        <div className="mt-2 max-w-prose text-sm leading-relaxed text-[rgb(var(--foreground))]">
          {description.split(/\n+/).map((para, i) => (
            <p key={i} className={i > 0 ? "mt-2" : undefined}>
              {para}
            </p>
          ))}
        </div>
      </section>

      <section aria-labelledby="combos-heading">
        <h2 id="combos-heading" className="text-lg font-semibold">
          Breeding combinations that produce {pal.name}
        </h2>
        <p className="mt-1 text-sm text-[rgb(var(--muted))]">
          Every parent pair that breeds into {pal.name}, ranked by obtainability.
          Looking for specific passives?{" "}
          <Link
            href={`/plan?target=${pal.slug}`}
            className="font-medium text-[rgb(var(--foreground))] hover:underline"
          >
            Plan a breed →
          </Link>
        </p>
        <div className="mt-3">
          <ReverseLookupTable pairs={pairs} />
        </div>
      </section>

      {related.length > 0 && (
        <section aria-labelledby="related-heading">
          <h2 id="related-heading" className="text-lg font-semibold">
            Related Pals
          </h2>
          <p className="mt-1 text-sm text-[rgb(var(--muted))]">
            Similar element, similar power value, or directly involved in {pal.name}&apos;s breeding lineage.
          </p>
          <ul className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">
            {related.map((r) => (
              <li key={r.id}>
                <Link
                  href={`/pals/${r.slug}`}
                  className="flex items-center gap-2 rounded-md border border-[rgb(var(--border))] p-2 hover:border-[rgb(var(--ring))]"
                >
                  <PalImage pal={r} />
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium">{r.name}</div>
                    <div className="text-xs text-[rgb(var(--muted))]">
                      #{String(r.paldexNo).padStart(3, "0")} · Power {r.powerValue}
                    </div>
                  </div>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section aria-labelledby="faq-heading">
        <h2 id="faq-heading" className="text-lg font-semibold">
          Frequently asked questions
        </h2>
        <dl className="mt-2 space-y-3">
          {faqs.map((q) => (
            <div
              key={q.question}
              className="rounded-md border border-[rgb(var(--border))] p-3"
            >
              <dt className="text-sm font-semibold">{q.question}</dt>
              <dd className="mt-1 text-sm text-[rgb(var(--muted))]">{q.answer}</dd>
            </div>
          ))}
        </dl>
      </section>

      {/* JSON-LD: Pal schema + FAQPage schema. Breadcrumb schema is emitted
          by the Breadcrumbs component itself. */}
      {/* eslint-disable-next-line @next/next/no-script-component-in-head */}
      <script {...jsonLd(palSchema(pal, { canonical: `/pals/${pal.slug}`, image: palImageForSchema }))} />
      {/* eslint-disable-next-line @next/next/no-script-component-in-head */}
      <script {...jsonLd(faqSchema(faqs))} />
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                   */
/* -------------------------------------------------------------------------- */

function resolvePairs(child: Pal): Array<{ parentA: Pal; parentB: Pal }> {
  const palMap = new Map(allPals.map((p) => [p.id, p]));
  return getParentPairsFor(child.id)
    .map((pair) => ({
      parentA: palMap.get(pair.parentA),
      parentB: palMap.get(pair.parentB),
    }))
    .filter(
      (p): p is { parentA: Pal; parentB: Pal } =>
        Boolean(p.parentA) && Boolean(p.parentB),
    );
}

/**
 * "Related" = same primary element OR within ±10% power value, ranked by
 * Paldex distance from this Pal. Excludes the Pal itself. Capped at `n`.
 *
 * This is internal-linking gold — every Pal page outbound-links to ~6 other
 * Pal pages, lifting the whole subgraph's link equity.
 */
function pickRelatedPals(pal: Pal, n: number): Pal[] {
  const sameElement = allPals.filter(
    (p) => p.id !== pal.id && p.elements[0] === pal.elements[0],
  );
  const similarPower = allPals.filter(
    (p) => p.id !== pal.id && Math.abs(p.powerValue - pal.powerValue) <= pal.powerValue * 0.1,
  );
  const candidatesById = new Map<string, Pal>();
  for (const p of [...sameElement, ...similarPower]) {
    if (!candidatesById.has(p.id)) candidatesById.set(p.id, p);
  }
  const ranked = [...candidatesById.values()].sort(
    (a, b) => Math.abs(a.paldexNo - pal.paldexNo) - Math.abs(b.paldexNo - pal.paldexNo),
  );
  return ranked.slice(0, n);
}

function buildFaqs(pal: Pal, pairCount: number): FaqEntry[] {
  const elements = pal.elements.join(" / ");
  const breedingLine = pairCount > 0
    ? `${pal.name} can be produced from ${pairCount} known parent pair${pairCount === 1 ? "" : "s"}, ranked on this page by obtainability.`
    : `Standard power-value breeding doesn't directly produce ${pal.name} in our current data. Special combinations may apply — check back as the dataset grows.`;
  const breedOnlyLine = pal.breedOnly
    ? `${pal.name} is breed-only: it doesn't appear in the wild and must be obtained through a specific parent pair.`
    : `${pal.name} can be encountered in the wild, but breeding for specific passives is usually faster than re-rolling captures.`;

  return [
    {
      question: `How do I get ${pal.name} in Palworld?`,
      answer: `${breedOnlyLine} ${breedingLine}`,
    },
    {
      question: `What element is ${pal.name}?`,
      answer: `${pal.name} is a ${elements} type Pal. Its primary element is ${pal.elements[0] ?? "Neutral"}, which determines its element-matched breeding pool.`,
    },
    {
      question: `What is ${pal.name}'s power value?`,
      answer: `${pal.name} has a power value of ${pal.powerValue}. The breeding engine uses this to compute the child of any pair as the floor of (parentA.powerValue + parentB.powerValue + 1) / 2 and pick the closest breedable Pal.`,
    },
    {
      question: `What's the best parent pair for ${pal.name}?`,
      answer:
        pairCount > 0
          ? `Pairs are ranked by obtainability on this page — lower Paldex numbers, matching primary elements, and avoiding breed-only intermediaries score higher. Use the planner to factor in your roster's existing passives.`
          : `Once parent pairs are known we'll list them here. In the meantime, the planner can search across your roster for any path that produces ${pal.name}.`,
    },
  ];
}
